name: Publish Figma Plugin
on:
  push:
    branches: [master, main, release]

jobs:
  publish_plugin:
    runs-on: ubuntu-latest
    env:
      FIGMA_TOKEN: ${{ secrets.FIGMA_TOKEN }}
      PLUGIN_ID: ${{ secrets.PLUGIN_ID }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Package plugin files
        run: |
          cd src
          zip -r ../plugin.zip *

      - name: Upload to Figma
        run: |
          curl -f -X POST \
            -H "X-Figma-Token:${FIGMA_TOKEN}" \
            -F "manifest=@src/manifest.json" \
            -F "bundle=@plugin.zip" \
            https://api.figma.com/v1/plugins/${PLUGIN_ID}/versions